export const DEFAULT_MAID_ANIMATIONS = [
  'touhou_little_maid:animation/maid/default/head/default.js',
  'touhou_little_maid:animation/maid/default/head/blink.js',
  'touhou_little_maid:animation/maid/default/head/beg.js',
  'touhou_little_maid:animation/maid/default/head/music_shake.js',
  'touhou_little_maid:animation/maid/default/leg/default.js',
  'touhou_little_maid:animation/maid/default/arm/default.js',
  'touhou_little_maid:animation/maid/default/arm/swing.js',
  'touhou_little_maid:animation/maid/default/arm/vertical.js',
  'touhou_little_maid:animation/maid/default/sit/default.js',
  'touhou_little_maid:animation/maid/default/armor/default.js',
  'touhou_little_maid:animation/maid/default/armor/reverse.js',
  'touhou_little_maid:animation/maid/default/wing/default.js',
  'touhou_little_maid:animation/maid/default/tail/default.js',
  'touhou_little_maid:animation/maid/default/sit/skirt_rotation.js',
  'touhou_little_maid:animation/base/float/default.js',
]

export const INNER_ANIMATION_IDS = new Set([
  ...DEFAULT_MAID_ANIMATIONS,
  'touhou_little_maid:animation/maid/default/head/ear_shake.js',
  'touhou_little_maid:animation/maid/default/head/ear_beg_shake.js',
  'touhou_little_maid:animation/maid/default/head/hair_swing.js',
  'touhou_little_maid:animation/maid/default/head/hair_ponytail_swing.js',
  'touhou_little_maid:animation/base/rotation/x_high_speed.js',
  'touhou_little_maid:animation/base/rotation/x_normal_speed.js',
  'touhou_little_maid:animation/base/rotation/x_low_speed.js',
  'touhou_little_maid:animation/base/rotation/y_high_speed.js',
  'touhou_little_maid:animation/base/rotation/y_normal_speed.js',
  'touhou_little_maid:animation/base/rotation/y_low_speed.js',
  'touhou_little_maid:animation/base/rotation/z_high_speed.js',
  'touhou_little_maid:animation/base/rotation/z_normal_speed.js',
  'touhou_little_maid:animation/base/rotation/z_low_speed.js',
])
